---
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
    enabled: yes
    daemon_reload: yes

- name: Restart fosdem_volunteers
  systemd:
    name: fosdem_volunteers
    state: restarted
    daemon_reload: yes
